### ISSUE TITLE
Cannot write to bitstream with dart package

### ISSUE THREAD

**Issue by jbrownsw** [beepltd/bitstream-dart#1]
I don't know if this is the right place to report this or not, but this is where the dart package links. I don't know if you actually created the dart package or someone just generated it from your repo or what. See https://pub.dev/packages/bitstream

None of this is probably an issue in your typescript and probably only applies to the dart generated code.

Anyway, you can't write to a Bitstream using the dart package because it increases the length property of the List<int>, but that throws an exception in dart for types that are not nullable which would never be the case here. Additionally I'd just like to mention that the constructor is a little odd that it takes Uint8List which is fine for reading, but would never be writeable because Uint8Lists are not growable so it would probably be better if it just took a List<int> which is what the member variable uses.

**Comment by edmundgentle** [comment]
Hi Steve, thanks for using Bitstream.
My pub.dev profile linked to the wrong repository (I moved this one to `bitstream-dart` and created the Typescript one as `bitstream`, but forgot to change the links on Pub.dev!) I've now resolved this, it should be correctly pointing to this repo!

I'm not sure what you mean about writing to the Bitstream, do you have sample code which isn't working?

That's a good point about the constructor. The project I was working on when I designed this involved pulling in a load of binary data as a `Uint8List` which is why I did it this way, but when I get a chance I may have a look at modifying the constructor to be a little more helpful. Or feel free to make the changes yourself if you'd like!

**Comment by jbrownsw** [comment]
I tested this with flutter 2.8.1 (dart 2.15.1).

Sample:
```
  var bs = BitStream();
  bs.write(0, bytes: 1);
```

Error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'int' in type cast
#0      List.length= (dart:core-patch/growable_array.dart:246:12)
#1      BitStream.write
package:bitstream/bitstream.dart:50
```

This happens because you can't do this (perhaps you could in older dart versions?):
```
      _stream.length = thisByte + 1;
```

Length setter code:
```
  void set length(int new_length) {
    if (new_length > length) {
      // Verify that element type is nullable.
      null as T; // Fails here because for List<int> int is not nullable
      if (new_length > _capacity) {
        _grow(new_length);
      }
      _setLength(new_length);
      return;
    }
```

So I really just don't see any possible way bitstream writing could even work right now because it can never extend the list to write anything to it.
